@startuml

actor User

package "Frontend" {
  [User Interface] as UI
  [Authentication] as Auth
  [Employee Management] as EM
}

package "Backend" {
  [API] as API
  [Authorization] as APIAuth
  [Employee Controller] as EC
  [Report Controller] as RC
  [Organization Controller] as OC
  [Employee Service Interface] as ESI
  [Report Service Interface] as RSI
  [Organization Service Interface] as OSI
  [User Service Interface] as USI
  [Employee Service] as ES
  [Report Service] as RS
  [Organization Service] as OS
  [Database Service] as DBS
  [User Controller] as UC
  [User Service] as US
}

database "Database" as DB

User --> UI
UI --> Auth
UI --> EM

Auth --> API : <<use>>
API ..> APIAuth : <<use>>

API -right-> EC
API -right-> RC
API -right-> OC
API -right-> UC

EC --> ESI : <<use>>
RC --> RSI : <<use>>
OC --> OSI : <<use>>
UC --> USI : <<use>>

ESI ..> ES
RSI ..> RS
OSI ..> OS
USI ..> US

ES --> DBS : <<use>>
RS --> DBS : <<use>>
OS --> DBS : <<use>>
US --> DBS : <<use>>

DBS --> DB

package "Tests" {
  [Frontend Tests] as FT
  [Backend Tests] as BT
}

FT --> UI : <<test>>
BT --> API : <<test>>

@enduml
